### PR TITLE
* Added tests for geospatial functions.

### PR DESCRIPTION
**Pull request by hylkevds**
I've written some tests for the geospatial filter functions.

### CODE REVIEW

**Comment by bertt** [comment]
Hi, trying to run the Geospatial functions test, but it stops in setting up database after 2 requests (creating things):

```
09:37:14.120 [main] INFO org.opengis.cite.sta10.filteringExtension.GeoTests - Setting up class.
09:37:15.545 [main] DEBUG de.fraunhofer.iosb.ilt.sta.dao.BaseDao - Posting to: http://localhost:8080/v1.0/Things
09:37:15.666 [main] DEBUG de.fraunhofer.iosb.ilt.sta.dao.BaseDao - Posting to: http://localhost:8080/v1.0/Things
09:37:15.675 [main] DEBUG de.fraunhofer.iosb.ilt.sta.dao.BaseDao - Posting to: http://localhost:8080/v1.0/Things

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

I suspect something with closing connections. First 2 things are created well. Any ideas how to fix?

**Comment by hylkevds** [comment]
Can you try running the tests in a debugger?
The exit code 130 is not a java exit code, but coming from the terminal. In bash 130 means it was iterrupted by the user pressing ctrl-c
SIGINT also means the process was stopped by an external signal...

**Comment by bertt** [comment]
yes I pressed control-c in IntelliJ because it hangs after 2 requests

**Comment by bertt** [comment]
Last line executed is L.74 in de.fraunhofer.iosb.ilt.sta.dao.BaseDao

```
                CloseableHttpResponse response = client.execute(httpPost);
```

**Comment by hylkevds** [comment]
So the server never responds to the http post?

**Comment by hylkevds** [comment]
Can you try increasing the version number of the SensorThingsClient to 0.11 in the pom of the testsuite?

**Comment by bertt** [comment]
on the server-side I see the first 2 requests ariving/handled but the third is not arriving it seems.

**Comment by bertt** [comment]
SensorThingsClient 0.11 is not found

**Comment by bertt** [comment]
tried with 0.6 and it runs :-)

**Comment by taniakhalafbeigi** [comment]
This PR uses a SensorThingsClient library. It means testing against SensorThings with a library that uses SensorThings but not tested against it.
In this case if there is any change to SensorThings that library needs to be updated as well as the ets-sta10 and that adds more delay. I would say if we want to use that library we'd better move the code here so that there is only one place we need to change.

**Comment by hylkevds** [comment]
Considering the speed of development of this test suit I really doubt there will be a problem with the library not being updated fast enough. 
But you can find it here: https://github.com/FraunhoferIOSB/FROST-Client so feel free to copy it into the project.

**Comment by taniakhalafbeigi** [comment]
Development speed of this test suite is irrelevant to the problem of this pull request. The OGC test suite should be self-contained with anything related to the standard that it is testing.

**Pull request closed without merging**
