### PR TITLE
MultiDatastream Extension tests

### LINKED ISSUE #39: Test-suite fails on any server that implements MultiDatastreams.
The current test-suite fails on any server that implements MultiDatastreams. Maybe someone can have a look at pull request #28 ?

### PR DESCRIPTION
**Pull request by hylkevds**
I've added some tests for the MultiDatastream Extension.

Fixes #39.

### CODE REVIEW

**Comment by dstenger** [comment]
Fixes #39.

**Comment by hylkevds** [comment]
If the library falls behind, you can always pull the library into the test suite at that point. Doing that when it's not needed is a (very) bad practice.

**Comment by taniakhalafbeigi** [comment]
What you are saying is correct in general for the libraries and that is why we use libraries in coding.
The problem here is different though. This is the test suite for SensorThings. The OGC test suite should be self-contained with anything related to the standard that it is testing.

**Comment by dstenger** [comment]
@hylkevds Do you consider this pull request worth/ valid to be merged? Or is it a better idea to create a new fix for https://github.com/opengeospatial/ets-sta10/issues/39 which is basing on the current status of the test suite?

**Pull request closed without merging**
